name: Build

"on":
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: agy-acp-windows
          path: target/release/*.exe
